apiVersion: v1
kind: Service
metadata:
  name: job-portal-web-service
  labels:
    app: job-portal-web
spec:
  type: NodePort
  selector:
    app: job-portal-web
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 32000
